### ISSUE TITLE
UMSocialCore/UMSocialCore.h' file not found

### ISSUE THREAD

**Issue by Yunnathai** [Timson020/react-native-umeng-api#1]
UMSocialCore/UMSocialCore.h' file not found

**Comment by Timson020** [comment]
https://github.com/Timson020/react-native-umeng-api#ios安装

step 1  can you do it ？

**Comment by loveshuffle** [comment]
@Timson020 step1: ios and reactnative's sdk all tried but failed,could you rewrite the api more clearly.
